@startuml
!define C4Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title Diagrama de Contexto - Sistema de Mala Direta

Person(Usuario, "Usuário", "Pessoa que utiliza o sistema para enviar mala direta")
System(SistemaMalaDireta, "MalaDiretaNodeJS", "Sistema para envio de mala direta")
Rel(Usuario, SistemaMalaDireta, "Envia dados para mala direta")

@enduml